import answerData from "../assets/items_list.json";

const staticImageMap = {
  Apple: require("../assets/images/Apple.jpg"),
  Phone: require("../assets/images/Phone.jpg"),
  Chair: require("../assets/images/Chair.jpg"),
  Table: require("../assets/images/Table.jpg"),
  Clock: require("../assets/images/Clock.jpg"),
  Brush: require("../assets/images/Brush.jpg"),
  Light: require("../assets/images/Light.jpg"),
  Piano: require("../assets/images/Piano.jpg"),
  Shelf: require("../assets/images/Shelf.jpg"),
  Frame: require("../assets/images/Frame.jpg"),
  Glass: require("../assets/images/Glass.jpg"),
  Spoon: require("../assets/images/Spoon.jpg"),
  Plate: require("../assets/images/Plate.jpg"),
  Knife: require("../assets/images/Knife.jpg"),
  Wheel: require("../assets/images/Wheel.jpg"),
  Bread: require("../assets/images/Bread.jpg"),
  Lemon: require("../assets/images/Lemon.jpg"),
  Peach: require("../assets/images/Peach.jpg"),
  Berry: require("../assets/images/Berry.jpg"),
  Mango: require("../assets/images/Mango.jpg"),
  Paper: require("../assets/images/Paper.jpg"),
  Stool: require("../assets/images/Stool.jpg"),
  Towel: require("../assets/images/Towel.jpg"),
  Cream: require("../assets/images/Cream.jpg"),
  Juice: require("../assets/images/Juice.jpg"),
  Plant: require("../assets/images/Plant.jpg"),
  Water: require("../assets/images/Water.jpg"),
  Grape: require("../assets/images/Grape.jpg"),
  Wheat: require("../assets/images/Wheat.jpg"),
  Coral: require("../assets/images/Coral.jpg"),
  Drill: require("../assets/images/Drill.jpg"),
  Wheel: require("../assets/images/Wheel.jpg"),
  Brick: require("../assets/images/Brick.jpg"),
  Scarf: require("../assets/images/Scarf.jpg"),
  Glove: require("../assets/images/Glove.jpg"),
  Boots: require("../assets/images/Boots.jpg"),
  Socks: require("../assets/images/Socks.jpg"),
  Shirt: require("../assets/images/Shirt.jpg"),
  Pants: require("../assets/images/Jeans.jpg"),
  Watch: require("../assets/images/Watch.jpg"),
  Chain: require("../assets/images/Chain.jpg"),
  Stamp: require("../assets/images/Stamp.jpg"),
  Plant: require("../assets/images/Plant.jpg"),
  Herbs: require("../assets/images/Herbs.jpg"),
  Metal: require("../assets/images/Metal.jpg"),
  Money: require("../assets/images/Money.jpg"),
  Honey: require("../assets/images/Honey.jpg"),
  Pasta: require("../assets/images/Pasta.jpg"),
  Sauce: require("../assets/images/Sauce.jpg"),
  Sugar: require("../assets/images/Sugar.jpg"),
  Eagle: require("../assets/images/Eagle.jpg"),
  Flute: require("../assets/images/Flute.jpg"),
  Cream: require("../assets/images/Cream.jpg"),
  Pouch: require("../assets/images/Pouch.jpg"),
  Daisy: require("../assets/images/Daisy.jpg"),
  Ocean: require("../assets/images/Ocean.jpg"),
  Wheat: require("../assets/images/Wheat.jpg"),
  Chili: require("../assets/images/Chili.jpg"),
  Fudge: require("../assets/images/Fudge.jpg"),
  Crumb: require("../assets/images/Crumb.jpg"),
  Cabin: require("../assets/images/Cabin.jpg"),
  Broom: require("../assets/images/Broom.jpg"),
  Shelf: require("../assets/images/Shelf.jpg"),
  Brush: require("../assets/images/Brush.jpg"),
  Clock: require("../assets/images/Clock.jpg"),
  Flute: require("../assets/images/Flute.jpg"),
  Ruler: require("../assets/images/Ruler.jpg"),
  Chalk: require("../assets/images/Chalk.jpg"),
  Maple: require("../assets/images/Maple.jpg"),
  Tulip: require("../assets/images/Tulip.jpg"),
  Zebra: require("../assets/images/Zebra.jpg"),
  Cloth: require("../assets/images/Cloth.jpg"),
  Swing: require("../assets/images/Swing.jpg"),
  Llama: require("../assets/images/Llama.jpg"),
  Skull: require("../assets/images/Skull.jpg"),
  Creek: require("../assets/images/Creek.jpg"),
  Chair: require("../assets/images/Chair.jpg"),
  Torch: require("../assets/images/Torch.jpg"),
  Scale: require("../assets/images/Scale.jpg"),
  Frame: require("../assets/images/Frame.jpg"),
  Table: require("../assets/images/Table.jpg"),
  Medal: require("../assets/images/Medal.jpg"),
  Crisp: require("../assets/images/Crisp.jpg"),
  Glass: require("../assets/images/Glass.jpg"),
  Piano: require("../assets/images/Piano.jpg"),
  Onion: require("../assets/images/Onion.jpg"),
  Donut: require("../assets/images/Donut.jpg"),
  Prism: require("../assets/images/Prism.jpg"),
  Boots: require("../assets/images/Boots.jpg"),
  Cello: require("../assets/images/Cello.jpg"),
  Grape: require("../assets/images/Grape.jpg"),
  Spoon: require("../assets/images/Spoon.jpg"),
  Train: require("../assets/images/Train.jpg"),
  Plate: require("../assets/images/Plate.jpg"),
  Shrub: require("../assets/images/Shrub.jpg"),
  Comic: require("../assets/images/Comic.jpg"),
  Clown: require("../assets/images/Clown.jpg"),
  Honey: require("../assets/images/Honey.jpg"),
  Knife: require("../assets/images/Knife.jpg"),
  Petal: require("../assets/images/Petal.jpg"),
};

const imageMap = () => {
  return answerData.map((item) => {
    return { name: item.name, source: staticImageMap[item.name] };
  });
};

export const imageSourceFinder = (currentName) => {
  const item = imageMap().find((item) => item.name === currentName);
  console.log(item, "item to be answer");
  return item ? item.source : undefined;
};
